name: earth-github-action-test CI
permissions:
  contents: write
# 하기 내용에 해당하는 이벤트 발생 시 github action 동작
on:
  pull_request: # feature/*와 develop 브랜치에서 PR이 일어났을 때 github action 동작
    branches:
      - 'feature/be/*'
      - 'develop'
      - 'master'
    path:
      - 'backend/**'

# 참고사항
# push가 일어난 브랜치에 PR이 존재하면, push에 대한 이벤트와 PR에 대한 이벤트 모두 발생합니다.

jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경 지정
    defaults:
      run:
        working-directory: ./backend # 작업 디렉토리 지정

    steps:
      - uses: actions/checkout@v2 # github action 버전 지정(major version)

      - name: Set up JDK 17 # JAVA 버전 지정
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle # 실제 application build(-x 옵션을 통해 test는 제외)
        run: ./gradlew build

      - name: Run tests with Gradle # test 실행
        run: ./gradlew test


#      - name: Publish Unit Test Results # test 후 result를 보기 위해 추가
#        uses: EnricoMi/publish-unit-test-result-action@v1
#        if: ${{ always() }} # test가 실패해도 report를 남기기 위해 설정
#        with:
#          files: backend/build/test-results/test/**/*.xml

